client
dev tun
proto udp

remote vpn-server 1194
resolv-retry infinite
nobind

persist-key
persist-tun

ca /etc/openvpn/certs/ca.crt
cert /etc/openvpn/certs/client.crt
key /etc/openvpn/certs/client.key

cipher AES-256-GCM
auth SHA256

verb 3
