FROM alpine:3.19

RUN apk add --no-cache openvpn curl iputils-ping

COPY vpn/client.conf /etc/openvpn/client.conf
COPY vpn/certs/ca.crt /etc/openvpn/certs/ca.crt
COPY vpn/certs/client.crt /etc/openvpn/certs/client.crt
COPY vpn/certs/client.key /etc/openvpn/certs/client.key

CMD ["openvpn", "--config", "/etc/openvpn/client.conf"]
